apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  nameSpace: wp-app
  name: pvc_claim_wordpress
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi