apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wp-app
  creationTimestamp: null
  labels:
    app: wp
  name: wp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp
  template:
    metadata:
      labels:
        app: wp
    spec:
      initContainers:
      - name: init-mysql
        image: mysql:5.7
        command: ['sh', '-c', 'until getent hosts mysql; do echo waiting for mysql; sleep 2; done;']
      containers:
      - image: wordpress
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              key: myusername
              name: envcm
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              key: mypass
              name: mysecret
        - name: WORDPRESS_DB_NAME
          value: wordpressdb
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-claim-wordpress
      
